/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi_Sewa;

/**
 *
 * @author intan
 */
import Koneksi_DB.Koneksi_DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Data_Costumer extends javax.swing.JFrame {

    /**
     * Creates new form Data_Costumer
     */
    private Connection koneksi;
    private Koneksi_DB db = new Koneksi_DB();
    public Data_Costumer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_jeniskelamin = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        intan_alamat = new javax.swing.JTextArea();
        intan_jenkel1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        intan_tabel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        intan_add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        intan_cancel = new javax.swing.JButton();
        intan_noktp = new javax.swing.JTextField();
        intan_tfcari = new javax.swing.JTextField();
        intan_tfnama = new javax.swing.JTextField();
        intan_cari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        intan_tfkontak = new javax.swing.JTextField();
        intan_update = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        intan_jenkel = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        intan_delete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        intan_exit = new javax.swing.JButton();
        intan_save = new javax.swing.JButton();
        intan_tfid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(214, 179, 255));

        btnmenu.setBackground(new java.awt.Color(51, 255, 51));
        btnmenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmenu.setText("Menu");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(51, 255, 51));
        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setText("X");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 954, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmenu)
                    .addComponent(btnclose))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1130, 60);

        jPanel1.setBackground(new java.awt.Color(242, 153, 232));

        intan_alamat.setColumns(20);
        intan_alamat.setRows(5);
        jScrollPane2.setViewportView(intan_alamat);

        btn_jeniskelamin.add(intan_jenkel1);
        intan_jenkel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_jenkel1.setText("Wanita");

        intan_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Costumer", "Nama Pegawai", "Alamat", "No KTP", "Kontak"
            }
        ));
        intan_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intan_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(intan_tabel);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("No KTP");

        intan_add.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_add.setForeground(new java.awt.Color(255, 153, 153));
        intan_add.setText("Add");
        intan_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_addActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Alamat");

        jk.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jk.setText("Jenis Kelamin");

        intan_cancel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_cancel.setForeground(new java.awt.Color(255, 153, 153));
        intan_cancel.setText("Cancel");
        intan_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_cancelActionPerformed(evt);
            }
        });

        intan_tfcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intan_tfcariMouseClicked(evt);
            }
        });

        intan_cari.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_cari.setForeground(new java.awt.Color(255, 153, 153));
        intan_cari.setText("Search");
        intan_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_cariActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("ID Costumer");

        intan_update.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_update.setForeground(new java.awt.Color(255, 153, 153));
        intan_update.setText("Update");
        intan_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_updateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Nama");

        btn_jeniskelamin.add(intan_jenkel);
        intan_jenkel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_jenkel.setText("Pria");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Kontak");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Data Costumer");

        intan_delete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_delete.setForeground(new java.awt.Color(255, 153, 153));
        intan_delete.setText("Delete");
        intan_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_deleteActionPerformed(evt);
            }
        });

        intan_exit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_exit.setForeground(new java.awt.Color(255, 153, 153));
        intan_exit.setText("Exit");
        intan_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_exitActionPerformed(evt);
            }
        });

        intan_save.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_save.setForeground(new java.awt.Color(255, 153, 153));
        intan_save.setText("Save");
        intan_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(intan_jenkel)
                                .addGap(18, 18, 18)
                                .addComponent(intan_jenkel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(intan_tfnama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(intan_tfid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(intan_tfkontak, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(intan_noktp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intan_add, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(intan_cari))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(intan_tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(intan_save)
                                .addGap(33, 33, 33)
                                .addComponent(intan_update)
                                .addGap(26, 26, 26)
                                .addComponent(intan_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(intan_cancel)
                                .addGap(30, 30, 30)
                                .addComponent(intan_exit))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(intan_tfid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(intan_tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jk)
                    .addComponent(intan_jenkel)
                    .addComponent(intan_jenkel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(intan_noktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(intan_tfkontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intan_add)
                    .addComponent(intan_update)
                    .addComponent(intan_delete)
                    .addComponent(intan_save)
                    .addComponent(intan_cancel)
                    .addComponent(intan_exit))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intan_tfcari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intan_cari))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 1130, 900);

        setSize(new java.awt.Dimension(1147, 974));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
     private void resettext(){
        intan_tfid.setText("");
        intan_tfnama.setText("");
        intan_alamat.setText("");
        intan_noktp.setText("");
        intan_tfkontak.setText("");   
    }
    
     public void getdata(){
    // Code Tampil Data
            DefaultTableModel tbm = new DefaultTableModel();
            //membuat nama kolom pada tabel
            tbm.addColumn("ID Costumer");
            tbm.addColumn("Nama Costumer");
            tbm.addColumn("Alamat");
            tbm.addColumn("No KTP");
            tbm.addColumn("Kontak");
            intan_tabel.setModel(tbm);
            db.koneksiDatabase();
            try {
            String query = "SELECT * FROM data_costumer";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
            tbm.addRow(new Object[]{
                rs.getString("id_costumer"),
                rs.getString("nama_costumer"),
                rs.getString("alamat_costumer"),
                rs.getString("no_ktp"),
                rs.getString("kontak_costumer"),
        });
        intan_tabel.setModel(tbm);
        }
        } catch (SQLException e)
        {
    }
 }
    
    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        Menu form;
        form = new Menu();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btncloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getdata();
    }//GEN-LAST:event_formWindowOpened

    private void intan_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_saveActionPerformed

        // Simpan Data
        db.koneksiDatabase();
        String jekel;
        boolean result = false;
        if(intan_jenkel.isSelected()){
            jekel = "Pria";
        }else{
            jekel = "Wanita";
        }

        // kode Simpan---------------
        String sql = "Insert Into data_costumer Values ('" + intan_tfid.getText() +
        "',  '" + intan_tfnama.getText() +
        "','" + jekel +
        "','" + intan_alamat.getText() +
        "','" + intan_tfkontak.getText() +
        "','" + intan_noktp.getText() +
        "')";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Simpan Sukses !");

            getdata();
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_intan_saveActionPerformed

    private void intan_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_exitActionPerformed
        dispose();
    }//GEN-LAST:event_intan_exitActionPerformed

    private void intan_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_deleteActionPerformed
        // Hapus Data
        db.koneksiDatabase();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
            "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
                String sql = "Delete FROM data_costumer where id_costumer  = '" + intan_tfid.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");

                getdata();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal"+e);
            }
        }
    }//GEN-LAST:event_intan_deleteActionPerformed

    private void intan_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_updateActionPerformed
        db.koneksiDatabase();
        boolean result = false;
        String jekel="";

        if(intan_jenkel.isSelected()){
            jekel="Pria";
        }else{
            jekel="Wanita";
        }

        try {
            String sql = "update data_costumer SET id_costumer ='"+ intan_tfid.getText()+
            "',nama_costumer = '" + intan_tfnama.getText()+
            "',jenis_kelamin = '"+jekel+
            "',alamat_costumer = '" + intan_alamat.getText()+
            "',no_ktp = '" + intan_noktp.getText()+
            "',kontak_costumer = '" + intan_tfkontak.getText()+
            "' WHERE id_costumer = '"+intan_tfid.getText()+
            "'";
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Update Sukses !");

            resettext();
            getdata();

        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_intan_updateActionPerformed

    private void intan_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_cariActionPerformed

        db.koneksiDatabase();
        String jenkel;
        boolean result = false;
        if(intan_jenkel.isSelected()){
            jenkel="Pria";
        }else{
            jenkel="Wanita";
        }

        // Cari Data
        db.koneksiDatabase();

        try {
            String query = "SELECT * FROM data_costumer where id_costumer = '" + intan_tfcari.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                intan_tfid.setText(rs.getString("id_costumer"));
                intan_tfnama.setText(rs.getString("nama_costumer"));
                intan_alamat.setText(rs.getString("alamat_costumer"));
                intan_noktp.setText(rs.getString("no_ktp"));
                intan_tfkontak.setText(rs.getString("kontak_costumer"));
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !" +e);
        }

        intan_tfcari.setText("");
    }//GEN-LAST:event_intan_cariActionPerformed

    private void intan_tfcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intan_tfcariMouseClicked

    }//GEN-LAST:event_intan_tfcariMouseClicked

    private void intan_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_cancelActionPerformed
        resettext();
        intan_tfid.requestFocus();
    }//GEN-LAST:event_intan_cancelActionPerformed

    private void intan_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_addActionPerformed
        resettext();
        intan_tfid.requestFocus();
    }//GEN-LAST:event_intan_addActionPerformed

    private void intan_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intan_tabelMouseClicked
        int row =intan_tabel.getSelectedRow();

        intan_tfid.setText(intan_tabel.getValueAt(row, 0).toString());
        intan_tfnama.setText(intan_tabel.getValueAt(row, 1).toString());
        intan_alamat.setText(intan_tabel.getValueAt(row, 2).toString());
        intan_noktp.setText(intan_tabel.getValueAt(row, 3).toString());
        intan_tfkontak.setText(intan_tabel.getValueAt(row, 4).toString());
    }//GEN-LAST:event_intan_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Costumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Costumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Costumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Costumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Costumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn_jeniskelamin;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton intan_add;
    private javax.swing.JTextArea intan_alamat;
    private javax.swing.JButton intan_cancel;
    private javax.swing.JButton intan_cari;
    private javax.swing.JButton intan_delete;
    private javax.swing.JButton intan_exit;
    private javax.swing.JRadioButton intan_jenkel;
    private javax.swing.JRadioButton intan_jenkel1;
    private javax.swing.JTextField intan_noktp;
    private javax.swing.JButton intan_save;
    private javax.swing.JTable intan_tabel;
    private javax.swing.JTextField intan_tfcari;
    private javax.swing.JTextField intan_tfid;
    private javax.swing.JTextField intan_tfkontak;
    private javax.swing.JTextField intan_tfnama;
    private javax.swing.JButton intan_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jk;
    // End of variables declaration//GEN-END:variables
}
