/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi_Sewa;

import Koneksi_DB.Koneksi_DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricop
 */
public class Data_Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Data_Transaksi
     */
    private Connection koneksi;
    private Koneksi_DB db = new Koneksi_DB();
    public boolean databaru;
    private PreparedStatement pst;
    public Data_Transaksi() {
        initComponents();
        idmobil();
        idcostumer();
        idpegawai();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        no_plat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        harga_sewa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        merek = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        intan_tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        intan_add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        intan_save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        intan_update = new javax.swing.JButton();
        id_transaksi = new javax.swing.JTextField();
        intan_delete = new javax.swing.JButton();
        kd_pegawai = new javax.swing.JComboBox();
        intan_cancel = new javax.swing.JButton();
        nama_costumer = new javax.swing.JTextField();
        intan_exit = new javax.swing.JButton();
        nama_pegawai = new javax.swing.JTextField();
        costumer = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_mobil = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        lama_sewa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total_sewa = new javax.swing.JTextField();
        tanggal_sewa = new com.toedter.calendar.JDateChooser();
        tanggal_kembali = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(214, 179, 255));

        btnmenu.setBackground(new java.awt.Color(51, 255, 51));
        btnmenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmenu.setText("Menu");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(51, 255, 51));
        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setText("X");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 845, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmenu)
                    .addComponent(btnclose))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1010, 60);

        jPanel3.setBackground(new java.awt.Color(242, 153, 232));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("No Plat");

        no_plat.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Harga Sewa");

        harga_sewa.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Merek");

        merek.setEditable(false);

        intan_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Tanggal Sewa", "Tanggal Kembali", "Lama Sewa", "Total Sewa"
            }
        ));
        intan_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intan_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(intan_tabel);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("No Transaksi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Tanggal Sewa");

        intan_add.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_add.setForeground(new java.awt.Color(255, 153, 153));
        intan_add.setText("Add");
        intan_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_addActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Costumer");

        intan_save.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_save.setForeground(new java.awt.Color(255, 153, 153));
        intan_save.setText("Save");
        intan_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_saveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Pegawai");

        intan_update.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_update.setForeground(new java.awt.Color(255, 153, 153));
        intan_update.setText("Update");
        intan_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_updateActionPerformed(evt);
            }
        });

        intan_delete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_delete.setForeground(new java.awt.Color(255, 153, 153));
        intan_delete.setText("Delete");
        intan_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_deleteActionPerformed(evt);
            }
        });

        kd_pegawai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kd_pegawaiItemStateChanged(evt);
            }
        });

        intan_cancel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_cancel.setForeground(new java.awt.Color(255, 153, 153));
        intan_cancel.setText("Cancel");
        intan_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_cancelActionPerformed(evt);
            }
        });

        nama_costumer.setEditable(false);

        intan_exit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_exit.setForeground(new java.awt.Color(255, 153, 153));
        intan_exit.setText("Exit");
        intan_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_exitActionPerformed(evt);
            }
        });

        nama_pegawai.setEditable(false);

        costumer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                costumerItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Form Sewa Mobil");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Id Mobil");

        id_mobil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                id_mobilItemStateChanged(evt);
            }
        });
        id_mobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id_mobilMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("Tanggal Kembali");

        lama_sewa.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("Lama Sewa");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Total Harga Sewa");

        total_sewa.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kd_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lama_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tanggal_kembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tanggal_sewa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(costumer, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id_transaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                .addGap(122, 706, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(85, 85, 85)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(44, 44, 44)
                                .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nama_costumer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nama_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(119, 119, 119)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(harga_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(intan_add)
                                .addGap(18, 18, 18)
                                .addComponent(intan_save)
                                .addGap(18, 18, 18)
                                .addComponent(intan_update)
                                .addGap(18, 18, 18)
                                .addComponent(intan_delete)
                                .addGap(18, 18, 18)
                                .addComponent(intan_cancel)
                                .addGap(18, 18, 18)
                                .addComponent(intan_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(34, 34, 34)
                                .addComponent(total_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(203, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggal_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(tanggal_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lama_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_costumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costumer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kd_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama_pegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no_plat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(total_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intan_add)
                    .addComponent(intan_save)
                    .addComponent(intan_update)
                    .addComponent(intan_delete)
                    .addComponent(intan_cancel)
                    .addComponent(intan_exit))
                .addGap(88, 88, 88))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 60, 1010, 990);

        setSize(new java.awt.Dimension(1029, 1060));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        Menu form;
        form = new Menu();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btncloseActionPerformed

     public void getdata(){
    // Code Tampil Data
            DefaultTableModel tbm = new DefaultTableModel();
            //membuat nama kolom pada tabel
            tbm.addColumn("No Transaksi");
            tbm.addColumn("Tanggal Sewa");
            tbm.addColumn("Tanggal Kembali");
            tbm.addColumn("Lama Sewa");
            tbm.addColumn("Total Sewa");
            intan_tabel.setModel(tbm);
            db.koneksiDatabase();
            try {
            String query = "SELECT * FROM data_transaksi";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
            tbm.addRow(new Object[]{
                rs.getString("id_transaksi"),
                rs.getString("tgl_pinjam"),
                rs.getString("tgl_kembali"),
                rs.getString("lama_sewa"),
                rs.getString("total_harga"),
        });
        intan_tabel.setModel(tbm);
        }
        } catch (SQLException e)
        {
            System.out.println(e);
    }
 }
    
    private void resettext(){
        //ADD
        id_transaksi.setText("");
        tanggal_sewa.setDate(null);
        id_mobil.setSelectedIndex(0);
        no_plat.setText("");
        costumer.setSelectedIndex(0);
        nama_costumer.setText("");
        kd_pegawai.setSelectedIndex(0);
        nama_pegawai.setText("");
        harga_sewa.setText("");
        merek.setText("");
        
    }
    
       public void tanggal(){
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        
        
        DateFormat dateAwal = new SimpleDateFormat("dd-MM-yyyy");
        DateFormat dateAkhir = new SimpleDateFormat("dd-MM-yyyy");
        
        try {
            Date tglAwal = dateAwal.parse(sdf.format(tanggal_sewa.getDate()));
            Date tglAkhir = dateAkhir.parse(sdf.format(tanggal_kembali.getDate()));
            
            Date TGLAwal = tglAwal;
            Date TGLAkhir = tglAkhir;
            Calendar cal1 = Calendar.getInstance();
            cal1.setTime(TGLAwal);
            Calendar cal2 = Calendar.getInstance();
            cal2.setTime(TGLAkhir);
            
            String hasil = String.valueOf(daysBetween(cal1, cal2));
            
            lama_sewa.setText(hasil);
            int total= Integer.valueOf(hasil);
            int a=Integer.valueOf(harga_sewa.getText());
            int kali=a*total;
            total_sewa.setText(Integer.toString(kali));
           
        } catch (ParseException e) {
        }
    }
    
     private static long daysBetween(Calendar tanggalAwal, Calendar tanggalAkhir) {
        long lama = 0;
        Calendar tanggal = (Calendar) tanggalAwal.clone();
        while (tanggal.before(tanggalAkhir)) {
            tanggal.add(Calendar.DAY_OF_MONTH, 1);
            lama++;
        }
        return lama;
    }
    
    private void idpegawai(){
                db.koneksiDatabase();
  
        try {
            String query = "SELECT * FROM data_pegawai";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {                
                kd_pegawai.addItem(rs.getString("id_pegawai"));
                nama_pegawai.setText(rs.getString("nama_pegawai"));
            } 
        } catch (SQLException e) {
        }
    }
    
    private void idcostumer(){
                db.koneksiDatabase();
  
        try {
            String query = "SELECT * FROM data_costumer";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {
                costumer.addItem(rs.getString("id_costumer"));
                nama_costumer.setText(rs.getString("nama_costumer"));
            } 
        } catch (SQLException e) {
        }
    }
    
     private void idmobil(){
                db.koneksiDatabase();
  
        try {
            String query = "SELECT * FROM data_mobil";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {       
                id_mobil.addItem(rs.getString("id_mobil"));
                no_plat.setText(rs.getString("no_plat"));
                merek.setText(rs.getString("merek"));
                harga_sewa.setText(rs.getString("harga_sewa"));
            } 
        } catch (SQLException e) {
        }
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getdata();
    }//GEN-LAST:event_formWindowOpened

    private void id_mobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id_mobilMouseClicked
        tanggal();
    }//GEN-LAST:event_id_mobilMouseClicked

    private void id_mobilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_id_mobilItemStateChanged
        String id;
        id=(String)id_mobil.getSelectedItem();
        no_plat.setText(id);
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM data_mobil where id_mobil= '" + id + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next())
            {
                no_plat.setText(rs.getString("no_plat"));
                merek.setText(rs.getString("merek"));
                harga_sewa.setText(rs.getString("harga_sewa"));
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");
        }
    }//GEN-LAST:event_id_mobilItemStateChanged

    private void costumerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_costumerItemStateChanged
        String id;
        id=(String)costumer.getSelectedItem();
        nama_costumer.setText(id);
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM data_costumer where id_costumer= '" + id + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next())
            {
                nama_costumer.setText(rs.getString("nama_costumer"));
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");
        }
    }//GEN-LAST:event_costumerItemStateChanged

    private void intan_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_intan_exitActionPerformed

    private void intan_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_cancelActionPerformed
        //CANCEL
        resettext();
    }//GEN-LAST:event_intan_cancelActionPerformed

    private void kd_pegawaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kd_pegawaiItemStateChanged
        String id;
        id=(String)kd_pegawai.getSelectedItem();
        nama_pegawai.setText(id);
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM data_pegawai where id_pegawai= '" + id + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next())
            {
                nama_pegawai.setText(rs.getString("nama_pegawai"));
            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");
        }
    }//GEN-LAST:event_kd_pegawaiItemStateChanged

    private void intan_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_deleteActionPerformed
        // Hapus Data
        db.koneksiDatabase();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
            "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
                String sql = "Delete FROM data_transaksi where id_transaksi  = '" + id_transaksi.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");

                getdata();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal"+e);
            }
        }
    }//GEN-LAST:event_intan_deleteActionPerformed

    private void intan_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_updateActionPerformed
        db.koneksiDatabase();
        boolean result = false;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            String sql = "update data_transaksi SET id_transaksi ='"+ id_transaksi.getText()+
            "',tgl_pinjam = '" + sdf.format(tanggal_sewa.getDate())+
            "',tgl_kembali = '" + sdf.format(tanggal_kembali.getDate())+
            "',lama_sewa = '" + lama_sewa.getText()+
            "',total_harga = '" + total_sewa.getText()+
            "' WHERE id_pegawai = '"+id_transaksi.getText()+
            "'";
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Update Sukses !");

            resettext();
            getdata();

        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        tanggal();
    }//GEN-LAST:event_intan_updateActionPerformed

    private void intan_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_saveActionPerformed
        db.koneksiDatabase();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String idmobil, kd_costumer, idpegawai, kode_barang ;
        kd_costumer= (String) costumer.getSelectedItem();
        idpegawai= (String) kd_pegawai.getSelectedItem();
        idmobil= (String) id_mobil.getSelectedItem();
        boolean result = false;
        boolean resultdetail = false;

        // kode Simpan---------------
        String sql = "Insert Into data_transaksi Values ('" + id_transaksi.getText() + "',  '" +
        kd_costumer + "','" +
        idmobil + "','" +
        idpegawai + "','" +
        sdf.format(tanggal_sewa.getDate()) + "','" +
        sdf.format(tanggal_kembali.getDate()) + "','" +
        lama_sewa.getText() + "','" +
        total_sewa.getText() + "' )";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Simpan");
            getdata();

            resettext();

        }catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        tanggal();
    }//GEN-LAST:event_intan_saveActionPerformed

    private void intan_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_addActionPerformed
        resettext();
    }//GEN-LAST:event_intan_addActionPerformed

    private void intan_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intan_tabelMouseClicked
        int row =intan_tabel.getSelectedRow();
        if(evt.getClickCount()==1){
            tanggal_sewa.setDate(getTanggalFromTable(intan_tabel, 1));
            tanggal_kembali.setDate(getTanggalFromTable(intan_tabel, 2));
        }
        id_transaksi.setText(intan_tabel.getValueAt(row, 0).toString());
        lama_sewa.setText(intan_tabel.getValueAt(row, 3).toString());
        total_sewa.setText(intan_tabel.getValueAt(row, 4).toString());
    }//GEN-LAST:event_intan_tabelMouseClicked

    public static Date getTanggalFromTable(JTable table, int kolom){
        JTable tabel = table;
        String str_tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), kolom));
        Date tanggal = null;
        try {
            tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(str_tgl);
        } catch (ParseException ex) {
            Logger.getLogger(Data_Transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tanggal;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnmenu;
    private javax.swing.JComboBox costumer;
    private javax.swing.JTextField harga_sewa;
    private javax.swing.JComboBox id_mobil;
    private javax.swing.JTextField id_transaksi;
    private javax.swing.JButton intan_add;
    private javax.swing.JButton intan_cancel;
    private javax.swing.JButton intan_delete;
    private javax.swing.JButton intan_exit;
    private javax.swing.JButton intan_save;
    private javax.swing.JTable intan_tabel;
    private javax.swing.JButton intan_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox kd_pegawai;
    private javax.swing.JTextField lama_sewa;
    private javax.swing.JTextField merek;
    private javax.swing.JTextField nama_costumer;
    private javax.swing.JTextField nama_pegawai;
    private javax.swing.JTextField no_plat;
    private com.toedter.calendar.JDateChooser tanggal_kembali;
    private com.toedter.calendar.JDateChooser tanggal_sewa;
    private javax.swing.JTextField total_sewa;
    // End of variables declaration//GEN-END:variables
}
