/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Aplikasi_Sewa;

import Koneksi_DB.Koneksi_DB;
import java.sql.Connection;
import Koneksi_DB.Koneksi_DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author intan
 */
public class Data_Mobil extends javax.swing.JFrame {

    /**
     * Creates new form Data_Mobil
     */
    private Connection koneksi;
    private Koneksi_DB db = new Koneksi_DB();
    public Data_Mobil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnmenu = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        no_plat = new javax.swing.JTextField();
        intan_add = new javax.swing.JButton();
        intan_update = new javax.swing.JButton();
        intan_delete = new javax.swing.JButton();
        intan_save = new javax.swing.JButton();
        intan_cancel = new javax.swing.JButton();
        intan_exit = new javax.swing.JButton();
        intan_btncari = new javax.swing.JButton();
        intan_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        intan_tabel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        merek = new javax.swing.JTextField();
        warna = new javax.swing.JTextField();
        harga_sewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(214, 179, 255));

        btnmenu.setBackground(new java.awt.Color(51, 255, 51));
        btnmenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmenu.setText("Menu");
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        btnclose.setBackground(new java.awt.Color(51, 255, 51));
        btnclose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnclose.setText("X");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 814, Short.MAX_VALUE)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmenu)
                    .addComponent(btnclose))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 990, 60);

        jPanel3.setBackground(new java.awt.Color(242, 153, 232));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("ID Mobil");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("No Plat");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Merek");

        intan_add.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_add.setForeground(new java.awt.Color(255, 153, 153));
        intan_add.setText("Add");
        intan_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_addActionPerformed(evt);
            }
        });

        intan_update.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_update.setForeground(new java.awt.Color(255, 153, 153));
        intan_update.setText("Update");
        intan_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_updateActionPerformed(evt);
            }
        });

        intan_delete.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_delete.setForeground(new java.awt.Color(255, 153, 153));
        intan_delete.setText("Delete");
        intan_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_deleteActionPerformed(evt);
            }
        });

        intan_save.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_save.setForeground(new java.awt.Color(255, 153, 153));
        intan_save.setText("Save");
        intan_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_saveActionPerformed(evt);
            }
        });

        intan_cancel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_cancel.setForeground(new java.awt.Color(255, 153, 153));
        intan_cancel.setText("Cancel");
        intan_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_cancelActionPerformed(evt);
            }
        });

        intan_exit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_exit.setForeground(new java.awt.Color(255, 153, 153));
        intan_exit.setText("Exit");
        intan_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_exitActionPerformed(evt);
            }
        });

        intan_btncari.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_btncari.setForeground(new java.awt.Color(255, 153, 153));
        intan_btncari.setText("Search");
        intan_btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intan_btncariActionPerformed(evt);
            }
        });

        intan_cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intan_cariMouseClicked(evt);
            }
        });

        intan_tabel.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        intan_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Mobil", "No Plat", "Merek Mobil", "Warna", "Harga Sewa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        intan_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intan_tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(intan_tabel);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Data Mobil");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Warna");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Harga Sewa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(intan_btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(intan_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(intan_add)
                                .addGap(18, 18, 18)
                                .addComponent(intan_save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(intan_update, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(intan_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(intan_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(intan_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(no_plat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(warna, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(harga_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 26, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(no_plat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(merek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(warna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(intan_add)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(intan_update)
                        .addComponent(intan_save)
                        .addComponent(intan_delete)
                        .addComponent(intan_cancel)
                        .addComponent(intan_exit)))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(intan_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intan_btncari))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 60, 990, 930);

        setSize(new java.awt.Dimension(1005, 1000));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        Menu form;
        form = new Menu();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmenuActionPerformed

     public void getdata(){
    // Code Tampil Data
            DefaultTableModel tbm = new DefaultTableModel();
            //membuat nama kolom pada tabel
            tbm.addColumn("ID Mobil");
            tbm.addColumn("No Plat");
            tbm.addColumn("Merek");
            tbm.addColumn("Warna");
            tbm.addColumn("Harga Sewa");
            intan_tabel.setModel(tbm);
            db.koneksiDatabase();
            try {
            String query = "SELECT * FROM data_mobil";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
            tbm.addRow(new Object[]{
                rs.getString("id_mobil"),
                rs.getString("no_plat"),
                rs.getString("merek"),
                rs.getString("warna"),
                rs.getString("harga_sewa"),
                
        });
        intan_tabel.setModel(tbm);
        }
        } catch (SQLException e)
        {
    }
 }
    
    
    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btncloseActionPerformed

    private void intan_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_addActionPerformed
        id.setText("");
        no_plat.setText("");
        merek.setText("");
        intan_cari.setText("");
    }//GEN-LAST:event_intan_addActionPerformed

    private void resettext(){
        id.setText("");
        no_plat.setText("");
        merek.setText("");
        warna.setText("");
    
    }
    
    private void intan_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_updateActionPerformed
        db.koneksiDatabase();
        boolean result = false;

        try {
            String sql = "update data_mobil SET id_mobil ='"+ id.getText()+
            "',no_plat = '" + no_plat.getText()+
            "',merek = '" + merek.getText()+
            "',warna = '" + warna.getText()+
            "',harga_sewa = '" + harga_sewa.getText()+
            "'";
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Update Sukses !");

            resettext();
            getdata();

        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_intan_updateActionPerformed

    private void intan_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_deleteActionPerformed
        // Hapus Data
        db.koneksiDatabase();
        int ok=JOptionPane.showConfirmDialog(null,"Apakah Yakin Mendelete record ini???",
            "Confirmation",JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
            try
            {
                String sql = "Delete FROM data_mobil where id_mobil = '" + id.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Delete Data Sukses");
                //   tekskosong();
                getdata();
            }
            catch (SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Delete Data Gagal");
            }
        }
    }//GEN-LAST:event_intan_deleteActionPerformed

    private void intan_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_saveActionPerformed
             // Simpan Data
        db.koneksiDatabase();
        boolean result = false;

        // kode Simpan---------------
        String sql = "Insert Into data_mobil Values ('" + id.getText() +
        "',  '" + no_plat.getText() +
        "','" + merek.getText() +
        "','" + warna.getText() +
        "','" + harga_sewa.getText() +
        "')";
        try {
            Statement st = db.getKoneksi().createStatement();
            st.executeUpdate(sql);
            result=true;
            JOptionPane.showMessageDialog(null, "Proses Simpan Sukses !");

            getdata();
        } catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_intan_saveActionPerformed

    private void intan_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_cancelActionPerformed
        id.setText("");
        no_plat.setText("");
        merek.setText("");
        warna.setText("");
        intan_cari.setText("");
    }//GEN-LAST:event_intan_cancelActionPerformed

    private void intan_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_exitActionPerformed
        dispose();
    }//GEN-LAST:event_intan_exitActionPerformed

    private void intan_btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intan_btncariActionPerformed
        // TODO add your handling code here:
        // Cari Data
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM data_mobil where id_mobil = '" + intan_cari.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                id.setText(rs.getString("id_user"));
                no_plat.setText(rs.getString("no_plat"));
                merek.setText(rs.getString("merek"));
                warna.setText(rs.getString("warna"));
                harga_sewa.setText(rs.getString("harga_sewa"));


            }
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan !");
        }
        intan_cari.setText("");
    }//GEN-LAST:event_intan_btncariActionPerformed

    private void intan_cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intan_cariMouseClicked

    }//GEN-LAST:event_intan_cariMouseClicked

    private void intan_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intan_tabelMouseClicked
         int row =intan_tabel.getSelectedRow();

        id.setText(intan_tabel.getValueAt(row, 0).toString());
        no_plat.setText(intan_tabel.getValueAt(row, 1).toString());
        merek.setText(intan_tabel.getValueAt(row, 2).toString());
        warna.setText(intan_tabel.getValueAt(row, 3).toString());
        harga_sewa.setText(intan_tabel.getValueAt(row, 4).toString());

    }//GEN-LAST:event_intan_tabelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getdata();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Mobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnmenu;
    private javax.swing.JTextField harga_sewa;
    private javax.swing.JTextField id;
    private javax.swing.JButton intan_add;
    private javax.swing.JButton intan_btncari;
    private javax.swing.JButton intan_cancel;
    private javax.swing.JTextField intan_cari;
    private javax.swing.JButton intan_delete;
    private javax.swing.JButton intan_exit;
    private javax.swing.JButton intan_save;
    private javax.swing.JTable intan_tabel;
    private javax.swing.JButton intan_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField merek;
    private javax.swing.JTextField no_plat;
    private javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables
}
